# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article_source_types', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=144)),
                ('article_source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_source_types.ArticleSourceType')),
            ],
        ),
    ]
