# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video_source_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=144)),
                ('video_source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_source_types.VideoSourceType')),
            ],
        ),
    ]
