# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
