# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20161027_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='source',
            field=models.CharField(max_length=500),
        ),
    ]
