# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('podcasts', '0004_auto_20161027_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='podcast',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
