# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 08:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
