# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20161121_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
