# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 21, 11, 15, 17, 520233)),
        ),
    ]
