# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20161121_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
