# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcast_source_types', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=144)),
                ('podcast_source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast_source_types.PodcastSourceType')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
